logging:
  level:
    root: ERROR
  file: log.log
flush_periods_s: 15
synth_flush_period_ms: 500
instruments:
    - name: BTCUSD
      instrument: BTC/USDT
    - name: ETHUSD
      instrument: ETH/USDT
    - name: BTCETH-synth1
      instrument: BTC/ETH
      depends:
        - BTC/USDT
        - ETH/USDT
    - name: ETHUSD-synth2
      instrument: ETH/USD
      depends:
        - ETH/BCH
        - USD/BCH
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptoharvester
    username: cryptoUser
    password: cryptoUser
  jpa:
    hibernate.ddl-auto: create-drop
